### ISSUE TITLE
请问下汉化是怎么处理呢

### ISSUE THREAD

**Issue by sewth** [yyong008/create-remix-antd-pro-app#1]
import { startTransition, useState } from 'react';
import { hydrateRoot } from 'react-dom/client';
import { RemixBrowser } from '@remix-run/react';

// components and others
import { createCache, StyleProvider } from '@ant-design/cssinjs';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN.js';

// context
import SettingContext from './settingContext';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn.js';
dayjs.locale('zh-cn');

const hydrate = () => {
    startTransition(() => {
        const cache = createCache();

        function MainApp() {
            const [theme, setTheme] = useState({
                colorPrimary: '#00b96b',
            });
            dayjs.locale('zh-cn');
            return (
                <SettingContext.Provider value={{ theme, setTheme }}>
                    <StyleProvider cache={cache}>
                        <ConfigProvider
                            theme={{
                                token: {
                                    colorPrimary: theme.colorPrimary,
                                },
                            }}
                            locale={zhCN}
                        >
                            <RemixBrowser />
                        </ConfigProvider>
                    </StyleProvider>
                </SettingContext.Provider>
            );
        }

        hydrateRoot(document, <MainApp />);
    });
};

if (typeof requestIdleCallback === 'function') {
    requestIdleCallback(hydrate);
} else {
    // Safari doesn't support requestIdleCallback
    // https://caniuse.com/requestidlecallback
    setTimeout(hydrate, 1);
}
 我这样改造后不生效，entry.server.tsx也做了处理

**Comment by yyong008** [comment]
看这个项目 https://github.com/yyong008/remix-antd-admin 吧，已经升级到了 v2 了，国际化使用的是 remix-i18n 和 react-i18n。

**Comment by sewth** [comment]
好的 谢谢

**Comment by sewth** [comment]
> 看这个项目 https://github.com/yyong008/remix-antd-admin 吧，已经升级到了 v2 了，国际化使用的是 remix-i18n 和 react-i18n。



> 看这个项目 https://github.com/yyong008/remix-antd-admin 吧，已经升级到了 v2 了，国际化使用的是 remix-i18n 和 react-i18n。

好的 谢谢
